import React,{useState,useEffect} from 'react';
import {View,Text,ScrollView,TextInput,TouchableOpacity,StyleSheet,Alert,ActivityIndicator,SafeAreaView,Modal,Linking,Share} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
const BACKEND_URL='https://your-advanced-backend.run.app';
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#0a0e27'},header:{backgroundColor:'#1a1f3a',padding:20,borderBottomWidth:2,borderBottomColor:'#00d4ff'},headerTitle:{fontSize:24,fontWeight:'bold',color:'#00d4ff'},headerSubtitle:{fontSize:11,color:'#00d4ff',opacity:.7,marginTop:4},tabs:{flexDirection:'row',backgroundColor:'#1a1f3a'},tab:{flex:1,paddingVertical:11,alignItems:'center'},active:{borderBottomWidth:3,borderBottomColor:'#00d4ff'},tabText:{fontSize:11,color:'#888'},activeText:{color:'#00d4ff'},content:{flex:1,padding:15},title:{fontSize:16,fontWeight:'700',color:'#00d4ff',marginBottom:12},input:{backgroundColor:'#1a1f3a',borderWidth:1,borderColor:'#333',borderRadius:8,padding:12,marginBottom:12,color:'#fff',fontSize:13},area:{height:180,textAlignVertical:'top',fontFamily:'Courier New'},button:{backgroundColor:'#00d4ff',padding:14,borderRadius:8,alignItems:'center',marginBottom:10},buttonText:{color:'#0a0e27',fontWeight:'bold'},card:{backgroundColor:'#1a1f3a',borderRadius:8,padding:14,marginBottom:12,borderLeftWidth:4,borderLeftColor:'#ff0055'},small:{fontSize:11,color:'#aaa',lineHeight:16},name:{fontSize:13,fontWeight:'bold',color:'#fff',marginBottom:6},gate:{backgroundColor:'#0d3b66',padding:12,borderRadius:8,marginBottom:12},gateTitle:{color:'#ff6b35',fontWeight:'bold',fontSize:11,marginBottom:5},report:{backgroundColor:'#1a1f3a',padding:14,borderRadius:8},reportText:{color:'#ccc',fontSize:11,lineHeight:18,fontFamily:'Courier New'}});
export default function AdvancedWeb3Scanner(){
 const [tab,setTab]=useState('opportunities'),[code,setCode]=useState(''),[name,setName]=useState(''),[loading,setLoading]=useState(false),[opps,setOpps]=useState([]),[findings,setFindings]=useState([]),[selected,setSelected]=useState(null),[modal,setModal]=useState(false),[url,setUrl]=useState(BACKEND_URL);
 useEffect(()=>{(async()=>{const u=await AsyncStorage.getItem('backendUrl');if(u)setUrl(u);const o=await AsyncStorage.getItem('opportunities');if(o)setOpps(JSON.parse(o));const f=await AsyncStorage.getItem('findings');if(f)setFindings(JSON.parse(f));})()},[]);
 const discover=async()=>{setLoading(true);try{const r=await fetch(`${url}/api/discover`,{method:'POST',headers:{'Content-Type':'application/json'}}),d=await r.json();if(!r.ok)throw Error(d.error||'Discovery failed');setOpps(d.opportunities||[]);await AsyncStorage.setItem('opportunities',JSON.stringify(d.opportunities||[]));}catch(e){Alert.alert('Discovery error',e.message)}finally{setLoading(false)}};
 const select=async o=>{try{const r=await fetch(`${url}/api/opportunities/${encodeURIComponent(o.id)}/select`,{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.error||'Selection failed');Alert.alert('Selected',`${o.name} is now Investigating.`)}catch(e){Alert.alert('Selection error',e.message)}};
 const analyze=async()=>{if(!code.trim()||!name.trim())return Alert.alert('Missing input','Enter protocol name and authorized code.');setLoading(true);try{const r=await fetch(`${url}/api/analyze-advanced`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,protocol_name:name})}),d=await r.json();if(!r.ok)throw Error(d.error||'Analysis failed');setFindings(d.detailed_reports||[]);await AsyncStorage.setItem('findings',JSON.stringify(d.detailed_reports||[]));setTab('findings')}catch(e){Alert.alert('Analysis error',e.message)}finally{setLoading(false)}};
 const opportunities=()=> <ScrollView style={styles.content}><Text style={styles.title}>Ranked Bounty Opportunities</Text><TouchableOpacity style={styles.button} onPress={discover} disabled={loading}><Text style={styles.buttonText}>{loading?'Discovering…':'Discover & Rank'}</Text></TouchableOpacity>{opps.map((o,i)=><TouchableOpacity style={styles.card} key={o.id} onPress={()=>select(o)}><Text style={styles.name}>#{i+1} {o.name}</Text><Text style={styles.small}>{String(o.source).toUpperCase()} • {o.status}</Text><Text style={styles.small}>Score: {o.score}/100 • Max bounty: ${Number(o.max_bounty_usd||0).toLocaleString()}</Text><Text style={styles.small}>~{o.estimated_hours}h • likelihood {Math.round((o.likelihood||0)*100)}% • difficulty {Math.round((o.difficulty||0)*100)}%</Text></TouchableOpacity>)}</ScrollView>;
 const analysis=()=> <ScrollView style={styles.content}><Text style={styles.title}>Authorized Protocol Analysis</Text><View style={styles.gate}><Text style={styles.gateTitle}>UNVERIFIED — HUMAN REVIEW REQUIRED</Text><Text style={styles.small}>Only analyze explicitly authorized bounty targets. Never test outside scope. Nothing is submitted automatically.</Text></View><TextInput style={styles.input} placeholder="Protocol name" value={name} onChangeText={setName} placeholderTextColor="#666"/><TextInput style={[styles.input,styles.area]} placeholder="Paste authorized Solidity/source code" value={code} onChangeText={setCode} multiline placeholderTextColor="#666"/><TouchableOpacity style={styles.button} onPress={analyze} disabled={loading}><Text style={styles.buttonText}>{loading?'Analyzing…':'Run Deep Analysis'}</Text></TouchableOpacity><Text style={styles.small}>State machine • business logic • access control • reentrancy/callbacks • oracle/price • economic attacks • arithmetic/edge cases</Text></ScrollView>;
 const result=()=> <ScrollView style={styles.content}><Text style={styles.title}>Findings — Human Verification Queue</Text>{findings.map(f=><TouchableOpacity key={f.finding_id} style={styles.card} onPress={()=>{setSelected(f);setModal(true)}}><Text style={styles.name}>{f.vulnerability}</Text><Text style={styles.small}>{String(f.severity).toUpperCase()} • confidence {Math.round((f.confidence||0)*100)}%</Text><Text style={styles.small}>UNVERIFIED — HUMAN REVIEW REQUIRED</Text></TouchableOpacity>)}</ScrollView>;
 return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.headerTitle}>🛡️ Web3 BugHunter</Text><Text style={styles.headerSubtitle}>Discover • Rank • Investigate • Validate • Human Review</Text></View><View style={styles.tabs}>{['opportunities','analyze','findings'].map(t=><TouchableOpacity key={t} style={[styles.tab,tab===t&&styles.active]} onPress={()=>setTab(t)}><Text style={[styles.tabText,tab===t&&styles.activeText]}>{t[0].toUpperCase()+t.slice(1)}</Text></TouchableOpacity>)}</View>{tab==='opportunities'?opportunities():tab==='analyze'?analysis():result()}<Modal visible={modal} animationType="slide"><SafeAreaView style={styles.container}><ScrollView style={styles.content}>{selected&&<><Text style={styles.title}>{selected.vulnerability}</Text><View style={styles.gate}><Text style={styles.gateTitle}>UNVERIFIED — HUMAN REVIEW REQUIRED</Text></View><View style={styles.report}><Text style={styles.reportText}>{selected.detailed_report}</Text></View><TouchableOpacity style={styles.button} onPress={()=>Share.share({message:selected.detailed_report,title:selected.vulnerability})}><Text style={styles.buttonText}>Share for Manual Review</Text></TouchableOpacity></>}<TouchableOpacity style={styles.button} onPress={()=>setModal(false)}><Text style={styles.buttonText}>Close</Text></TouchableOpacity></ScrollView></SafeAreaView></Modal></SafeAreaView>;
}
