package com.web3bughunter.android

import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.datastore.preferences.core.*
import androidx.datastore.preferences.preferencesDataStore
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.net.URLEncoder
import java.util.concurrent.TimeUnit

private val Context.settings by preferencesDataStore("settings")
private val BASE = stringPreferencesKey("backend_url")
private const val HUMAN_REVIEW = "UNVERIFIED — HUMAN REVIEW REQUIRED"
private const val DEFAULT_BACKEND = "https://web3-bughunter.onrender.com"
const val API_CALL_TIMEOUT_SECONDS = 180L

data class AuthorizationState(val evidence:String="",val backendVerified:Boolean=false,val confirmed:Boolean=false){val verified:Boolean get()=backendVerified&&confirmed}
class Api(private val context:Context){
 private val client=OkHttpClient.Builder().connectTimeout(30,TimeUnit.SECONDS).readTimeout(API_CALL_TIMEOUT_SECONDS,TimeUnit.SECONDS).writeTimeout(30,TimeUnit.SECONDS).callTimeout(API_CALL_TIMEOUT_SECONDS,TimeUnit.SECONDS).build()
 suspend fun base():String=context.settings.data.first()[BASE]?:DEFAULT_BACKEND
 suspend fun saveBase(v:String){val value=v.trim().trimEnd('/');require(value.startsWith("https://")){"Backend URL must use HTTPS."};context.settings.edit{it[BASE]=value}}
 suspend fun call(path:String,method:String="GET",body:JSONObject?=null):JSONObject=withContext(Dispatchers.IO){val base=base().ifBlank{throw IllegalStateException("The production backend URL is not configured.")};require(base.startsWith("https://")){"Backend URL must use HTTPS."};val rb=body?.toString()?.toRequestBody("application/json".toMediaType());val req=Request.Builder().url(base+path).method(method,if(method=="GET")null else rb).build();client.newCall(req).execute().use{r->val text=r.body?.string().orEmpty();if(!r.isSuccessful){val sm=runCatching{JSONObject(text).optString("error")}.getOrNull().orEmpty();throw UserFacingException(if(r.code==403)"This action is blocked because backend authorization has not been verified for this opportunity." else if(sm.isNotBlank())sm else "The request could not be completed (HTTP ${r.code}).")};JSONObject(text)}}
}
class UserFacingException(message:String):Exception(message)
data class Opp(val id:String,val name:String,val source:String,val status:String,val score:Double,val bounty:Double,val likelihood:Double,val difficulty:Double,val raw:JSONObject)
data class Target(val kind:String,val identifier:String,val sourceUrl:String,val address:String)
data class Finding(val id:String,val title:String,val severity:String,val confidence:Double,val description:String,val evidence:String,val status:String)
enum class Screen{OPPORTUNITIES,TARGET,ANALYZE,FINDINGS,QUEUE,HISTORY,SETTINGS}
class MainVm(private val api:Api):ViewModel(){
 var url by mutableStateOf("");var screen by mutableStateOf(Screen.OPPORTUNITIES);var busy by mutableStateOf(false);var error by mutableStateOf("");var notice by mutableStateOf("");var opps by mutableStateOf(listOf<Opp>());var selectedOpp by mutableStateOf<Opp?>(null);var targets by mutableStateOf(listOf<Target>());var scopeRules by mutableStateOf("");var exclusions by mutableStateOf(listOf<String>());var scopeEvidence by mutableStateOf("");var authorization by mutableStateOf(AuthorizationState());var acquiredPath by mutableStateOf("");var findings by mutableStateOf(listOf<Finding>());var report by mutableStateOf("");var queueText by mutableStateOf("");var historyText by mutableStateOf("");var selectedFinding by mutableStateOf<Finding?>(null)
 init{viewModelScope.launch{url=api.base()}}
 private fun run(block:suspend()->Unit)=viewModelScope.launch{busy=true;error="";notice="";try{block()}catch(e:Exception){error=e.message?:"The operation could not be completed."}finally{busy=false}}
 fun saveUrl(v:String)=run{api.saveBase(v);url=api.base();notice="Backend URL saved."}
 fun discover()=run{val d=api.call("/api/discover","POST",JSONObject());opps=parseOpps(d.optJSONArray("opportunities"));notice="Discovery completed: ${opps.size} opportunities available."}
 fun select(o:Opp)=run{api.call("/api/opportunities/${URLEncoder.encode(o.id,"UTF-8")}/select","POST",JSONObject());selectedOpp=o;authorization=AuthorizationState();scopeEvidence="";loadPlanInternal(o);screen=Screen.TARGET}
 fun loadPlan()=selectedOpp?.let{run{loadPlanInternal(it)}}
 private suspend fun loadPlanInternal(o:Opp){val evidence=buildString{append(o.raw.optString("scope_notes"));append('\n');append(o.raw.optJSONObject("metadata")?.toString().orEmpty());append('\n');append(o.raw.optString("url"))}.trim();val d=api.call("/api/research/plan","POST",JSONObject().put("opportunity",o.raw).put("public_evidence",evidence));val scope=d.optJSONObject("scope")?:JSONObject();val auth=d.optJSONObject("authorization")?:JSONObject();scopeEvidence=scope.optString("scope_evidence").ifBlank{evidence};scopeRules=scope.optString("rules");exclusions=jsonStrings(scope.optJSONArray("exclusions"));val a=d.optJSONArray("targets")?:JSONArray();targets=(0 until a.length()).map{val x=a.getJSONObject(it);Target(x.optString("kind"),x.optString("identifier"),x.optString("source_url"),x.optString("address"))};authorization=AuthorizationState(scopeEvidence,auth.optBoolean("verified",false),false);notice=if(authorization.backendVerified)"Backend authorization is verified. Review the target and confirm before protected research." else "No backend authorization is verified for this opportunity. Public scope evidence does not authorize testing; protected research remains blocked."}
 fun setAuthorizationConfirmed(v:Boolean){authorization=authorization.copy(confirmed=v)}
 fun acquire(t:Target)=run{if(!authorization.verified)throw UserFacingException("Repository acquisition is blocked until backend authorization is verified and you confirm the authorized target.");if(t.kind=="evm_contract"||t.sourceUrl.isBlank())throw UserFacingException("This EVM/on-chain target is in scope, but repository acquisition is unavailable because the backend only acquires public GitHub repositories.");val d=api.call("/api/research/acquire","POST",JSONObject().put("opportunity_id",selectedOpp?.id).put("target",JSONObject().put("name",selectedOpp?.name?:"authorized-target").put("source_url",t.sourceUrl).put("kind",t.kind).put("scope_evidence",scopeEvidence)));if(!d.optBoolean("ok"))throw UserFacingException(d.optString("reason",d.optString("error","Target acquisition was blocked.")));acquiredPath=d.optString("path");notice="Authorized repository acquired on the research backend.";screen=Screen.ANALYZE}
 fun analyze()=run{if(!authorization.verified)throw UserFacingException("Analysis is blocked: backend authorization has not been verified for this opportunity.");if(acquiredPath.isBlank())throw UserFacingException("Acquire an authorized GitHub repository before source-backed analysis.");val d=api.call("/api/research/analyze","POST",JSONObject().put("opportunity_id",selectedOpp?.id).put("source_dir",acquiredPath).put("protocol_name",selectedOpp?.name?:"authorized-target"));findings=parseFindings(d.optJSONArray("correlated_findings"));notice=if(findings.isEmpty())"Analysis completed with no correlated findings." else "Analysis completed. Findings remain unverified and require human review.";screen=Screen.FINDINGS}
 fun fuzz()=run{if(!authorization.verified||acquiredPath.isBlank())throw UserFacingException("Fuzzing is blocked until backend authorization is verified and an authorized repository is acquired.");api.call("/api/security-tools/fuzz","POST",JSONObject().put("opportunity_id",selectedOpp?.id).put("source_dir",acquiredPath).put("framework","auto").put("timeout",180).put("findings",JSONArray(findings.map{JSONObject().put("id",it.id).put("title",it.title).put("severity",it.severity).put("description",it.description)})));notice="Bounded validation completed."}
 fun duplicateCheck(f:Finding)=run{val d=api.call("/api/research/duplicate-check","POST",JSONObject().put("finding",JSONObject().put("id",f.id).put("title",f.title).put("severity",f.severity).put("description",f.description).put("evidence",f.evidence)));val n=d.optJSONArray("matches")?.length()?:0;notice=if(n==0)"No similarity matches were returned. This is not a duplicate determination." else "$n possible historical match(es) returned. Human review is required."}
 fun economic(f:Finding)=run{if(!authorization.verified)throw UserFacingException("Economic analysis is blocked until backend authorization is verified.");val d=api.call("/api/research/economic-analysis","POST",JSONObject().put("opportunity_id",selectedOpp?.id).put("finding",JSONObject().put("id",f.id).put("title",f.title).put("severity",f.severity).put("description",f.description)));notice="Economic analysis completed. ${d.optString("status").ifBlank{"Review the result with the finding."}}"}
 fun generateReport()=run{val a=JSONArray(findings.map{JSONObject().put("id",it.id).put("title",it.title).put("severity",it.severity).put("confidence",it.confidence).put("description",it.description).put("evidence",JSONArray(listOf(it.evidence))).put("status",HUMAN_REVIEW)});val d=api.call("/api/generate-human-review-report","POST",JSONObject().put("findings",a).put("opportunity",selectedOpp?.raw?:JSONObject()));report=d.optJSONObject("report")?.toString(2)?:d.toString(2);screen=Screen.FINDINGS;notice="Professional report generated for human review. Nothing has been submitted."}
 fun loadQueue()=run{queueText=api.call("/api/research/queue").toString(2)};fun loadHistory()=run{historyText=api.call("/api/hunting-history").toString(2)}
 private fun parseOpps(a:JSONArray?):List<Opp> = a?.let{arr->(0 until arr.length()).map{i->val o=arr.getJSONObject(i);Opp(o.optString("id"),o.optString("name"),o.optString("source"),o.optString("status"),o.optDouble("score"),o.optDouble("max_bounty_usd"),o.optDouble("likelihood"),o.optDouble("difficulty"),o)}}?:emptyList()
 private fun parseFindings(a:JSONArray?):List<Finding> = a?.let{arr->(0 until arr.length()).map{i->val f=arr.getJSONObject(i);Finding(f.optString("id"),f.optString("title",f.optString("vulnerability","Finding")),f.optString("severity","medium"),f.optDouble("confidence"),f.optString("description"),f.optJSONArray("evidence")?.toString().orEmpty(),HUMAN_REVIEW)}}?:emptyList()
 private fun jsonStrings(a:JSONArray?):List<String> = a?.let{arr->(0 until arr.length()).map{i->arr.optString(i)}}?:emptyList()
}
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App(MainVm(Api(this)))}}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun App(vm:MainVm){MaterialTheme{Scaffold(topBar={TopAppBar(title={Text("Web3 BugHunter",fontWeight=FontWeight.Bold)})}){p->Column(Modifier.padding(p).fillMaxSize()){if(vm.error.isNotBlank())Text(vm.error,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(12.dp));if(vm.notice.isNotBlank())Text(vm.notice,modifier=Modifier.padding(12.dp));val screens=Screen.values().toList();ScrollableTabRow(selectedTabIndex=screens.indexOf(vm.screen)){screens.forEach{s->Tab(vm.screen==s,onClick={vm.screen=s},text={Text(s.name.lowercase().replace('_',' ').replaceFirstChar{it.uppercase()})})}};when(vm.screen){Screen.OPPORTUNITIES->Opps(vm);Screen.TARGET->TargetScreen(vm);Screen.ANALYZE->AnalyzeScreen(vm);Screen.FINDINGS->FindingsScreen(vm);Screen.QUEUE->QueueScreen(vm);Screen.HISTORY->HistoryScreen(vm);Screen.SETTINGS->Settings(vm)}}}}}
@Composable fun Opps(vm:MainVm){Column(Modifier.padding(12.dp).fillMaxSize()){Button(onClick={vm.discover()},enabled=!vm.busy,modifier=Modifier.fillMaxWidth()){Text(if(vm.busy)"Discovering…" else "Discover & Rank")};LazyColumn{items(vm.opps){o->Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(12.dp)){Text(o.name,fontWeight=FontWeight.Bold);Text("${o.source.uppercase()} • ${o.status}");Text("Score ${o.score}/100 • max bounty $${o.bounty.toInt()}");Text("Likelihood ${(o.likelihood*100).toInt()}% • difficulty ${(o.difficulty*100).toInt()}%");Button(onClick={vm.select(o)},enabled=!vm.busy){Text("Select & investigate")}}}}}}}
@Composable fun TargetScreen(vm:MainVm){Column(Modifier.padding(12.dp).fillMaxSize()){Text("Target & authorization",style=MaterialTheme.typography.titleLarge);vm.selectedOpp?.let{Text(it.name,fontWeight=FontWeight.Bold)};Text("Public discovery and scope evidence do not establish authorization. The backend must verify authorization before protected research is enabled.",Modifier.padding(vertical=8.dp));if(vm.scopeEvidence.isNotBlank())Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text("Public scope evidence",fontWeight=FontWeight.Bold);Text(vm.scopeEvidence)}};if(vm.scopeRules.isNotBlank())Text("Rules: ${vm.scopeRules}",Modifier.padding(vertical=6.dp));if(vm.exclusions.isNotEmpty())Text("Exclusions: ${vm.exclusions.joinToString()}",Modifier.padding(vertical=6.dp));Text("Targets",fontWeight=FontWeight.Bold,Modifier.padding(top=8.dp));LazyColumn{items(vm.targets){t->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(10.dp)){Text(t.identifier.ifBlank{t.address},fontWeight=FontWeight.Bold);Text(if(t.kind=="evm_contract")"EVM/on-chain contract target — repository acquisition unavailable" else "GitHub repository target");if(t.kind!="evm_contract"&&t.sourceUrl.isNotBlank())Button(onClick={vm.acquire(t)},enabled=!vm.busy&&vm.authorization.verified){Text("Acquire authorized repository")}}}}};if(vm.authorization.backendVerified){Row(verticalAlignment=androidx.compose.ui.Alignment.CenterVertically){Checkbox(checked=vm.authorization.confirmed,onCheckedChange={vm.setAuthorizationConfirmed(it)});Text("I have personally verified that the selected target is authorized and in scope using the published evidence.")}}else Text("Authorization cannot be established from this client. No backend-verified authorization record is available for this opportunity.",fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=10.dp));Text(if(vm.authorization.verified)"Backend authorization verified and client confirmation recorded for this session." else "Protected research remains blocked.",Modifier.padding(top=8.dp),fontWeight=FontWeight.Bold)}}
@Composable fun AnalyzeScreen(vm:MainVm){Column(Modifier.padding(12.dp).fillMaxSize()){Text("Authorized research",style=MaterialTheme.typography.titleLarge);Text("Acquired target: ${vm.acquiredPath.ifBlank{"none"}}");Text(HUMAN_REVIEW,Modifier.padding(vertical=6.dp),fontWeight=FontWeight.Bold);Button(onClick={vm.analyze()},enabled=!vm.busy&&vm.authorization.verified&&vm.acquiredPath.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Analyze authorized target")};Button(onClick={vm.fuzz()},enabled=!vm.busy&&vm.authorization.verified&&vm.acquiredPath.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Run bounded fuzz/validation")}}}
@Composable fun FindingsScreen(vm:MainVm){Column(Modifier.padding(12.dp).fillMaxSize()){Text("Findings & evidence",style=MaterialTheme.typography.titleLarge);Text(HUMAN_REVIEW,Modifier, fontWeight=FontWeight.Bold);if(vm.findings.isNotEmpty())Button(onClick={vm.generateReport()},enabled=!vm.busy,modifier=Modifier.fillMaxWidth()){Text("Generate professional human-review report")};if(vm.report.isNotBlank())Text(vm.report,Modifier.padding(vertical=8.dp));LazyColumn{items(vm.findings){f->Card(onClick={vm.selectedFinding=f},modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(10.dp)){Text(f.title,fontWeight=FontWeight.Bold);Text("${f.severity.uppercase()} • confidence ${(f.confidence*100).toInt()}%");Text(f.status)}}}};vm.selectedFinding?.let{f->AlertDialog(onDismissRequest={vm.selectedFinding=null},confirmButton={TextButton(onClick={vm.selectedFinding=null}){Text("Close")}},title={Text(f.title)},text={Column{Text(HUMAN_REVIEW,fontWeight=FontWeight.Bold);Text(f.description);Text("Evidence",fontWeight=FontWeight.Bold);Text(f.evidence);Row{TextButton(onClick={vm.duplicateCheck(f)}){Text("Check duplicates")};TextButton(onClick={vm.economic(f)}){Text("Economic analysis")}}}})}}}
@Composable fun QueueScreen(vm:MainVm){Column(Modifier.padding(12.dp)){Text("Research queue",style=MaterialTheme.typography.titleLarge);Button(onClick={vm.loadQueue()}){Text("Refresh queue")};if(vm.queueText.isNotBlank())Text(vm.queueText)}}
@Composable fun HistoryScreen(vm:MainVm){Column(Modifier.padding(12.dp)){Text("Hunting history",style=MaterialTheme.typography.titleLarge);Button(onClick={vm.loadHistory()}){Text("Refresh history")};if(vm.historyText.isNotBlank())Text(vm.historyText)}}
@Composable fun Settings(vm:MainVm){var u by remember(vm.url){mutableStateOf(vm.url)};Column(Modifier.padding(12.dp)){Text("Backend",style=MaterialTheme.typography.titleLarge);Text("Production backend is HTTPS-only.");OutlinedTextField(value=u,onValueChange={u=it},label={Text("HTTPS backend URL")},modifier=Modifier.fillMaxWidth());Button(onClick={vm.saveUrl(u)},enabled=!vm.busy){Text("Save backend URL")};Text("Automatic bounty submission is disabled. Findings remain unverified and reports require human verification and manual submission.")}}
